
services:
  appserver:
    depends_on:
      - mysql
    container_name: server
    hostname: localhost
    image: pintop9/backend
    ports:
      - 8080:8080
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Unix11
      MYSQL_DATABASE: students
      MYSQL_USER: devopsdemo
      MYSQL_PASSWORD: Mypassw07d!
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    #privileged: true
