
services:
  appserver:
    depends_on:
      - mysql
    container_name: server
    hostname: localhost
    image: pintop9/backend
    ports:
      - 8080:8080
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: students
      MYSQL_USER: devopsdemo
      MYSQL_PASSWORD: /run/secrets/db_user_password
    ports:
      - 3306:3306
    secrets:
       - root_password
       - user_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    #privileged: true
secrets:
  root_password:
    file: ./db_root_password.txt
  user_password:
    file: ./db_user_password.txt 