version: "3.8"

services:
  appserver:
    depends_on:
      - mysql
    container_name: server
    hostname: localhost
    image: pintop9/backend:latest
    ports:
      - 8080:8080

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: students
      MYSQL_USER: devopsdemo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
