name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  APP_VERSION: v1.0.${{ github.run_number }}

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 25
        uses: actions/setup-java@v2
        with:
          java-version: '25.0.1+8.0.LTS'
          distribution: 'adopt'
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: mvn clean install
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ env.APP_VERSION }}
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }} # store the SSH password as a secret in the repository
          script: |
            sudo yum update -y
            sudo yum install -y docker git
            sudo service docker start
            sudo usermod -aG docker ec2-user  # allows running docker without sudo
            DOCKER_COMPOSE_VERSION="v2.40.1"
            sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            [ -d "/home/ec2-user/ops-basic-spring/.git" ] && cd /home/ec2-user/ops-basic-spring && git fetch origin && git reset --hard origin/master || git clone https://github.com/pintop9/ops-basic-spring.git /home/ec2-user/ops-basic-spring
            cd ./ops-basic-spring
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            sed -i "s|image: pintop9/backend:.*|image: pintop9/backend:v1.0.${{ github.run_number }}|g" docker-compose-aws.yml
            docker-compose -f docker-compose-aws.yml down || true
            docker-compose -f docker-compose-aws.yml up -d 
